# Generated by Django 4.1.1 on 2022-09-20 08:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('b_no', models.AutoField(primary_key=True, serialize=False)),
                ('b_title', models.CharField(max_length=300)),
                ('b_content', models.TextField()),
                ('b_hit', models.IntegerField(default=0)),
                ('b_date', models.DateTimeField(default=datetime.datetime(2022, 9, 20, 17, 36, 43, 336952))),
            ],
        ),
    ]
