# Generated by Django 4.1.1 on 2022-09-22 05:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('s_no', models.AutoField(primary_key=True, serialize=False)),
                ('s_name', models.CharField(max_length=100)),
                ('s_major', models.CharField(max_length=100)),
                ('s_age', models.IntegerField(default=0)),
                ('s_grade', models.IntegerField(default=0)),
                ('s_gender', models.CharField(max_length=30)),
                ('s_date', models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 22, 14, 33, 31, 557549))),
            ],
        ),
    ]
